services:
    - type: web
      name: growtime-backend
      runtime: docker
      plan: free
      region: oregon
      branch: master
      dockerfilePath: ./Dockerfile
      dockerContext: .
      healthCheckPath: /actuator/health
      autoDeployTrigger: off
      envVars:
          - key: PORT
            value: "8196"
          - key: SPRING_DATASOURCE_URL
            sync: false
          - key: SPRING_DATASOURCE_USERNAME
            sync: false
          - key: SPRING_DATASOURCE_PASSWORD
            sync: false
          - key: GITHUB_CLIENT_ID
            sync: false
          - key: GITHUB_CLIENT_SECRET
            sync: false
          - key: APP_JWT_SECRET
            sync: false
          - key: APP_JWT_EXPIRATION_SECONDS
            value: "86400"
          - key: APP_CORS_ALLOWED_ORIGINS
            value: https://growtime-frontend-nine.vercel.app
